class ServiceTypes:
    Agriculture = "agriculture"
    Clock = "clock"
    Cluster = "cluster"
    Czml = "czml"
    Data = "data"
    Groundstation = "groundstation"
    Iot = "iot"
    Orbits = "orbits"
    RL = "rl"
    RL_Training = "rl_training"
    Logging = "logging"
    Config = "config"
    Template = "template"
